project:
  type: website

website:
  title: "Matt Spence"
  site-url: https://www.mattspence.com
  description: "This is Matt Spence's personal landing page and occasional blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: Posts
    right:
      - icon: github
        href: https://github.com/mattspence
      - icon: mastodon
        href: https://mastodon.social/@mattspence
      # - icon: rss
        # href: blog.xml
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



