project:
  type: website

website:
  title: "Matt Spence"
  site-url: https://mattspence.github.io
  description: "This is Matt Spence's personal landing page and occasional blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - href: work/index.qmd
      #   text: Recent Work
      - href: posts/index.qmd
        text: Posts
    right:
      - icon: github
        href: https://github.com/mattspence
  repo-url: https://github.com/mattspence/mattspence.github.io
  repo-actions: [edit, issue]

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



